
// This file has been generated by the GUI designer. Do not modify.

public partial class LoginWindow
{
	private global::Gtk.VBox vbox;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Entry in_login;
	
	private global::Gtk.Entry in_password;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label lbl_login;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Statusbar status_login;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget LoginWindow
		this.Name = "LoginWindow";
		this.Title = "RFUpdater";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(1));
		this.Resizable = false;
		// Container child LoginWindow.Gtk.Container+ContainerChild
		this.vbox = new global::Gtk.VBox ();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 2;
		this.vbox.BorderWidth = ((uint)(6));
		// Container child vbox.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.in_login = new global::Gtk.Entry ();
		this.in_login.CanFocus = true;
		this.in_login.Name = "in_login";
		this.in_login.IsEditable = true;
		this.in_login.InvisibleChar = '•';
		this.table1.Add (this.in_login);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.in_login]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.in_password = new global::Gtk.Entry ();
		this.in_password.CanFocus = true;
		this.in_password.Name = "in_password";
		this.in_password.IsEditable = true;
		this.in_password.InvisibleChar = '•';
		this.table1.Add (this.in_password);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.in_password]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lbl_login = new global::Gtk.Label ();
		this.lbl_login.Name = "lbl_login";
		this.lbl_login.LabelProp = global::Mono.Unix.Catalog.GetString ("Login");
		this.table1.Add (this.lbl_login);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lbl_login]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox.Add (this.table1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox [this.table1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Submit");
		this.vbox.Add (this.button2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox [this.button2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.status_login = new global::Gtk.Statusbar ();
		this.status_login.Name = "status_login";
		this.status_login.Homogeneous = true;
		this.status_login.Spacing = 6;
		this.status_login.HasResizeGrip = false;
		this.vbox.Add (this.status_login);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox [this.status_login]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 2;
		w7.Expand = false;
		this.Add (this.vbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 233;
		this.DefaultHeight = 124;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler (this.login);
	}
}
