
// This file has been generated by the GUI designer. Do not modify.
namespace RFUpdater
{
	public partial class SettingRow
	{
		private global::Gtk.HBox hbox;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RFUpdater.SettingRow
			global::Stetic.BinContainer.Attach(this);
			this.Name = "RFUpdater.SettingRow";
			// Container child RFUpdater.SettingRow.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			this.Add(this.hbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
