
// This file has been generated by the GUI designer. Do not modify.
namespace RFUpdater
{
	public partial class ModuleWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry in_name;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label lbl_version;
		
		private global::Gtk.Entry in_version;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Entry in_realeaseDate;
		
		private global::Gtk.Label lbl_releaseDate;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.CheckButton chk_mandatory;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.Label lbl_crc;
		
		private global::Gtk.Entry in_crc;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label lbl_moduleDependancies;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label lbl_moduleConflicts;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Button btn_newVersion;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RFUpdater.ModuleWindow
			this.Name = "RFUpdater.ModuleWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ModuleWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child RFUpdater.ModuleWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox4.Add (this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.in_name = new global::Gtk.Entry ();
			this.in_name.Sensitive = false;
			this.in_name.CanFocus = true;
			this.in_name.Name = "in_name";
			this.in_name.IsEditable = false;
			this.in_name.InvisibleChar = '●';
			this.hbox4.Add (this.in_name);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.in_name]));
			w2.Position = 1;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w3.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lbl_version = new global::Gtk.Label ();
			this.lbl_version.Name = "lbl_version";
			this.lbl_version.LabelProp = global::Mono.Unix.Catalog.GetString ("Version");
			this.hbox5.Add (this.lbl_version);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lbl_version]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.in_version = new global::Gtk.Entry ();
			this.in_version.Sensitive = false;
			this.in_version.CanFocus = true;
			this.in_version.Name = "in_version";
			this.in_version.IsEditable = false;
			this.in_version.InvisibleChar = '●';
			this.hbox5.Add (this.in_version);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.in_version]));
			w5.Position = 1;
			this.hbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox5]));
			w6.Position = 1;
			w6.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.in_realeaseDate = new global::Gtk.Entry ();
			this.in_realeaseDate.Sensitive = false;
			this.in_realeaseDate.CanFocus = true;
			this.in_realeaseDate.Name = "in_realeaseDate";
			this.in_realeaseDate.IsEditable = false;
			this.in_realeaseDate.InvisibleChar = '●';
			this.hbox6.Add (this.in_realeaseDate);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.in_realeaseDate]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lbl_releaseDate = new global::Gtk.Label ();
			this.lbl_releaseDate.Name = "lbl_releaseDate";
			this.lbl_releaseDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Release");
			this.hbox6.Add (this.lbl_releaseDate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lbl_releaseDate]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox6]));
			w9.Position = 2;
			w9.Expand = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow.Add (this.treeview2);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w12.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.chk_mandatory = new global::Gtk.CheckButton ();
			this.chk_mandatory.Sensitive = false;
			this.chk_mandatory.CanFocus = true;
			this.chk_mandatory.Name = "chk_mandatory";
			this.chk_mandatory.Label = global::Mono.Unix.Catalog.GetString ("Mandatory module");
			this.chk_mandatory.Active = true;
			this.chk_mandatory.DrawIndicator = true;
			this.chk_mandatory.UseUnderline = true;
			this.hbox14.Add (this.chk_mandatory);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.chk_mandatory]));
			w13.Position = 0;
			this.hbox12.Add (this.hbox14);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hbox14]));
			w14.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.lbl_crc = new global::Gtk.Label ();
			this.lbl_crc.Name = "lbl_crc";
			this.lbl_crc.LabelProp = global::Mono.Unix.Catalog.GetString ("Crc");
			this.hbox13.Add (this.lbl_crc);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.lbl_crc]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.in_crc = new global::Gtk.Entry ();
			this.in_crc.Sensitive = false;
			this.in_crc.CanFocus = true;
			this.in_crc.Name = "in_crc";
			this.in_crc.IsEditable = true;
			this.in_crc.InvisibleChar = '●';
			this.hbox13.Add (this.in_crc);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.in_crc]));
			w16.Position = 1;
			this.hbox12.Add (this.hbox13);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hbox13]));
			w17.Position = 1;
			this.vbox2.Add (this.hbox12);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Module dependancies");
			this.hbox8.Add (this.label7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label7]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lbl_moduleDependancies = new global::Gtk.Label ();
			this.lbl_moduleDependancies.Name = "lbl_moduleDependancies";
			this.lbl_moduleDependancies.LabelProp = global::Mono.Unix.Catalog.GetString ("list of modules");
			this.hbox8.Add (this.lbl_moduleDependancies);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lbl_moduleDependancies]));
			w20.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Select dependancies...");
			this.hbox8.Add (this.button1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button1]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Modules conflicts");
			this.hbox9.Add (this.label8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lbl_moduleConflicts = new global::Gtk.Label ();
			this.lbl_moduleConflicts.Name = "lbl_moduleConflicts";
			this.lbl_moduleConflicts.LabelProp = global::Mono.Unix.Catalog.GetString ("list of modules");
			this.hbox9.Add (this.lbl_moduleConflicts);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lbl_moduleConflicts]));
			w24.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Select conflicts modules...");
			this.hbox9.Add (this.button2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button2]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox2.Add (this.hbox9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox11.Add (this.button3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button3]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Validate");
			this.hbox11.Add (this.button4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button4]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btn_newVersion = new global::Gtk.Button ();
			this.btn_newVersion.CanFocus = true;
			this.btn_newVersion.Name = "btn_newVersion";
			this.btn_newVersion.UseUnderline = true;
			this.btn_newVersion.Label = global::Mono.Unix.Catalog.GetString ("Create new version");
			this.hbox11.Add (this.btn_newVersion);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btn_newVersion]));
			w29.PackType = ((global::Gtk.PackType)(1));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox2.Add (this.hbox11);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox11]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 822;
			this.DefaultHeight = 322;
			this.Show ();
		}
	}
}
